import { query } from "../config/db.js";

// "Session" is the DB/internal term for what the product calls a "Run".
// user_id is auto-populated by the trigger_set_session_user_id trigger
// (mirrors the existing set_request_user_id convention on `requests`), and
// share_token is auto-generated by the column default — neither is set here.
class Session {
  static async create({ apiKey, name = null, hostname = null }) {
    const sql = `
      INSERT INTO sessions (api_key, name, hostname)
      VALUES ($1, $2, $3)
      RETURNING *
    `;
    const values = [apiKey, name, hostname];
    const result = await query(sql, values);
    return result.rows[0];
  }

  static async end(id) {
    const sql = `
      UPDATE sessions SET ended_at = now()
      WHERE id = $1
      RETURNING *
    `;
    const result = await query(sql, [id]);
    return result.rows[0] || null;
  }

  static async findById(id) {
    const sql = 'SELECT * FROM sessions WHERE id = $1';
    const result = await query(sql, [id]);
    return result.rows[0] || null;
  }

  static async findByApiKey(apiKey) {
    const sql = 'SELECT * FROM sessions WHERE api_key = $1 ORDER BY started_at DESC';
    const result = await query(sql, [apiKey]);
    return result.rows;
  }

  static async findByShareToken(token) {
    const sql = 'SELECT * FROM sessions WHERE share_token = $1';
    const result = await query(sql, [token]);
    return result.rows[0] || null;
  }
}

export default Session;